language: ruby

rvm:
  - 1.9.3
  - 2.1.2
  - jruby
  - rubinius

env:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.2

matrix:
  exclude:
    - rvm: jruby
      env: RAILS_VERSION=3.2
    - rvm: rubinius
      env: RAILS_VERSION=3.2
  allow_failures:
    - rvm: jruby
    - rvm: rubinius
